// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RadzenApp.Model.Scan;

public partial class ScanRequest
{
    public int ScanRequestId { get; set; }

    public string DeploymentLocation { get; set; }

    public virtual ICollection<Technology> Technologies { get; set; } = new List<Technology>();
}