// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RadzenApp.Model.Scan;

public partial class Technology
{
    public int TechnologyId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<ScanRequest> ScanRequests { get; set; } = new List<ScanRequest>();
}