// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RadzenApp.Model.Scan;

public partial class WebApp
{
    public int WebAppId { get; set; }

    public string AppName { get; set; }

    public string AppUrl { get; set; }

    public string AppDescription { get; set; }

    public DateTime? CreateTs { get; set; }

    public string CreateBy { get; set; }

    public DateTime? EditTs { get; set; }

    public string EditBy { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<WebAppPerson> WebAppPeople { get; set; } = new List<WebAppPerson>();
}