// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RadzenApp.Model.Scan;

public partial class WebAppPerson
{
    public int WebAppId { get; set; }

    public int PersonNumber { get; set; }

    public string Type { get; set; }

    public string Name { get; set; }

    public string Department { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public virtual WebApp WebApp { get; set; }
}